apiVersion: v1
kind: Secret
metadata:
  name: db-cred
  namespace: xhcp 
  annotations:
    # (Opsiyonel) referans için; esas değerler aşağıda <path:...> placeholder ile çekiliyor
    avp.kubernetes.io/path: "kv/data/app/config"
type: Opaque
stringData:
  DB_USER: <path:test/opt/test/config#data.DB_USER>
