apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: xhcp
  # KRİTİK DÜZELTME: AVP'nin KV V2 motorunda veriye ulaşması için 
  # path'e "data/" katmanını ekliyoruz. 
  annotations:
    avp.kubernetes.io/path: "argocd/data/test" # MUTLAK YOL ŞİMDİ DOĞRU
type: Opaque
stringData:
  # Yer tutucu sadece çekilecek KEY'i belirtir. Path artık annotation'dadır.
  # Placeholder: <path:#data.<KEY>>
  DB_USER: <path:#data.DB_USER> 

#apiVersion: v1
#kind: Secret
#metadata:
#  name: demo-secret
#  namespace: xhcp
#  annotations:
#    avp.kubernetes.io/path: "argocd/data/test"
#type: Opaque
#stringData:
#  DB_USER: <path:secret/data/argocd/test#data.DB_USER>
