#apiVersion: v1
#kind: Secret
#metadata:
#  name: demo-secret
#  namespace: xhcp
#  annotations:
#    avp.kubernetes.io/path: "argocd/data/test"
#type: Opaque
#stringData:
#  DB_USER: <path:secret/data/argocd/test#data.DB_USER>


apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: xhcp
  # KRİTİK DÜZELTME: AVP'ye, sadece bu annotation'daki 
  # yolu (sizin Vault'ta çalışan yolu) kullanmasını söylüyoruz.
  annotations:
    avp.kubernetes.io/path: "argocd/test" # Sizin Vault path'iniz.
type: Opaque
stringData:
  # Yer tutucu sadece çekilecek KEY'i belirtir. Path artık annotation'dadır.
  DB_USER: <path:#data.DB_USER> 
