apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: xhcp
  # KRİTİK DÜZELTME: AVP'nin KV V2 motorunda veriye ulaşması için 
  # path'e "data/" katmanını ekliyoruz. 
  annotations:
    avp.kubernetes.io/path: "argocd/data/test" # MUTLAK YOL ŞİMDİ DOĞRU
type: Opaque
stringData:
  # YENİ DÜZELTME: Annotation kullanıldığı için, yer tutucuyu en basit 
  # formuna getiriyoruz. Sadece Secret'ın KEY'ini belirtir.
  # Placeholder: <KEY>
  DB_USER: <DB_USER> 


#apiVersion: v1
#kind: Secret
#metadata:
#  name: demo-secret
#  namespace: xhcp
#  annotations:
#    avp.kubernetes.io/path: "argocd/data/test"
#type: Opaque
#stringData:
#  DB_USER: <path:secret/data/argocd/test#data.DB_USER>
