apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: xhcp
  annotations:
    avp.kubernetes.io/path: "argocd/data/test"
type: Opaque
stringData:
  DB_USER: <path:secret/data/argocd/test#data.DB_USER>
